from __future__ import annotations

import json
from collections.abc import Callable
from dataclasses import dataclass
from typing import Protocol, cast
from urllib import request

OPENROUTER_EMBEDDINGS_URL = "https://openrouter.ai/api/v1/embeddings"
HttpPost = Callable[[str, dict[str, object], dict[str, str], float], dict[str, object]]


@dataclass(frozen=True)
class Embedding:
    """Vector generated by an embedding provider."""

    provider: str
    model: str
    vector: list[float]

    @property
    def dimensions(self) -> int:
        """Return vector dimensionality."""
        return len(self.vector)


class Embedder(Protocol):
    """Embedding provider contract."""

    def embed(self, text: str) -> Embedding:
        """Embed one text string."""


class OpenRouterEmbedder:
    """OpenRouter embeddings provider."""

    def __init__(
        self,
        *,
        api_key: str,
        model: str,
        dimensions: int | None = None,
        post_json: HttpPost | None = None,
        timeout: float = 30.0,
    ) -> None:
        """Create an OpenRouter embedder."""
        if not api_key:
            msg = "OpenRouter API key is required"
            raise ValueError(msg)
        self._api_key = api_key
        self._model = model
        self._dimensions = dimensions
        self._post_json = post_json or _post_json
        self._timeout = timeout

    def embed(self, text: str) -> Embedding:
        """Embed one text string through OpenRouter."""
        payload: dict[str, object] = {"input": text, "model": self._model}
        if self._dimensions is not None:
            payload["dimensions"] = self._dimensions
        response = self._post_json(
            OPENROUTER_EMBEDDINGS_URL,
            payload,
            {
                "Authorization": f"Bearer {self._api_key}",
                "Content-Type": "application/json",
            },
            self._timeout,
        )
        return Embedding(
            provider="openrouter",
            model=str(response.get("model", self._model)),
            vector=_embedding_vector(response),
        )


def _post_json(
    url: str,
    payload: dict[str, object],
    headers: dict[str, str],
    timeout: float,
) -> dict[str, object]:
    if not url.startswith("https://"):
        msg = "Only HTTPS embedding endpoints are supported"
        raise ValueError(msg)
    body = json.dumps(payload).encode("utf-8")
    req = request.Request(url, data=body, headers=headers, method="POST")  # noqa: S310
    with request.urlopen(req, timeout=timeout) as response:  # noqa: S310
        return json.loads(response.read().decode("utf-8"))


def _embedding_vector(response: dict[str, object]) -> list[float]:
    data = response.get("data")
    if not isinstance(data, list) or not data:
        msg = "OpenRouter embedding response did not include data"
        raise ValueError(msg)
    first = data[0]
    if not isinstance(first, dict):
        msg = "OpenRouter embedding response data item was invalid"
        raise TypeError(msg)
    first_item = cast("dict[str, object]", first)
    embedding = first_item.get("embedding")
    if not isinstance(embedding, list):
        msg = "OpenRouter embedding response did not include an embedding vector"
        raise TypeError(msg)
    return [_float_value(value) for value in embedding]


def _float_value(value: object) -> float:
    if isinstance(value, int | float):
        return float(value)
    msg = "OpenRouter embedding vector contained a non-numeric value"
    raise ValueError(msg)
